#
#  Multi machine, essential options Vagrant file example. (documentation removed)
#

#  Inline provisioning script

$script = <<SCRIPT
INTERFACE=`ip a|grep ^2: |awk -F":" '{print $2}'`
sudo rm -fr /etc/sysconfig/network-scripts/ifcfg-$INTERFACE
sudo /usr/bin/nmcli con mod "System$INTERFACE" ipv4.addresses ${1}${2} ipv4.method manual ipv4.gateway $3 ipv4.dns 192.168.86.1
sudo /usr/bin/nmcli con mod "System$INTERFACE" connection.autoconnect on
sudo systemctl disable firewalld
SCRIPT


nodes = [
  { hostname: 'k3-master', box: 'generic/centos7', ip: '192.168.86.101'},
  { hostname: 'k3-node-1', box: 'generic/centos7', ip: '192.168.86.102'},
  { hostname: 'k3-node-2', box: 'generic/centos7', ip: '192.168.86.103' }
]

Vagrant.configure('2') do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.hostname = node[:hostname]
      node_config.vm.box = node[:box]
      #node_config.vm.synced_folder('.', '/Vagrantfiles', type: 'rsync')
      node_config.vm.provision "shell" do |s|
        s.inline = $script
        s.args   = [ node[:ip], "/24" , "192.168.86.1" ]
      end
    end
    
  end

  config.vm.provider :vmware_esxi do |esxi|
    #
    #   Provider settings
    #
    esxi.esxi_hostname = '192.168.86.66'
    esxi.esxi_username = 'root'
    esxi.esxi_password = 'prompt:'
    #esxi.esxi_hostport = 22
    esxi.esxi_virtual_network = 'VM_Network'
    #esxi.esxi_disk_store = 'DS_001'
    #esxi.esxi_resource_pool = '/Vagrant'
    esxi.guest_memsize = '2048'
    esxi.guest_numvcpus = '2'
  end

  
end