---

- name: Download k3s binary x64
  get_url:                                                           
    url: "https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 755
    checksum: sha256:8aed3abe7af30adbe44b70a6a774b205d1c403c3b35fcd4aa558b3cb413fcba5
