# - name: update host file
#   lineinfile:
#     dest: /etc/hosts
#     regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
#     line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
#     state: present
#   become: yes
#   with_items: "{{ groups.all }}"
- name: generate host file
  template:
    src: "hosts.j2"
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
- name: Install libselinux as prerequisite for SELinux Ansible module
  yum:
    name: ['libselinux-python','libsemanage-python']
    state: latest

- name: Disable SELinux at next reboot
  selinux:
    state: disabled

- name: Set SELinux in permissive mode until the machine is rebooted
  command: setenforce 0
  ignore_errors: true
  changed_when: false

- name: make .ssh direcotry
  file:
    path: "/home/vagrant/.ssh"
    state: directory
- name: create authorized keys  file
  file:
    path: "/home/vagrant/.ssh/authorized_keys"
    state: touch
- name: put pubkey
  lineinfile:
    path: "/home/vagrant/.ssh/authorized_keys"
    line: "{{ ssh_public_key }}"